<template>
  <div v-if="visible" class="fixed inset-0 z-50" @click.self="$emit('close')">
    <div class="fixed inset-0 bg-black/40 backdrop-blur-sm" @click="$emit('close')"></div>
    <div class="fixed top-0 right-0 h-full w-full max-w-3xl bg-white dark:bg-surface-800 shadow-2xl animate-slide-in-right flex flex-col">
      <!-- Header -->
      <div class="flex items-center justify-between px-6 py-4 border-b border-surface-200 dark:border-surface-700 flex-shrink-0">
        <div class="flex items-center gap-3">
          <div class="w-9 h-9 bg-gradient-to-br from-purple-500 to-purple-600 rounded-xl flex items-center justify-center shadow-sm">
            <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/>
            </svg>
          </div>
          <div>
            <h3 class="text-lg font-bold text-surface-800 dark:text-white">{{ isEditing ? $t('coupons.editCoupon') : $t('coupons.addCoupon') }}</h3>
            <p class="text-xs text-surface-400">{{ isEditing ? $t('coupons.editDesc') : $t('coupons.createDesc') }}</p>
          </div>
        </div>
        <button @click="$emit('close')" class="p-2 text-surface-400 hover:text-surface-600 hover:bg-surface-100 dark:hover:bg-surface-700 rounded-lg transition-colors">
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
        </button>
      </div>

      <!-- Form Body -->
      <div class="flex-1 overflow-y-auto px-6 py-5">
        <form @submit.prevent="save" class="space-y-5">
          <!-- Name & Code -->
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-surface-700 dark:text-surface-200 mb-1.5">{{ $t('coupons.couponName') }} *</label>
              <input v-model="form.name" required maxlength="100"
                class="w-full px-3.5 py-2.5 border border-surface-200 dark:border-surface-600 bg-white dark:bg-surface-700 text-surface-800 dark:text-white rounded-lg text-sm focus:ring-2 focus:ring-purple-500/50 transition-all" />
            </div>
            <div>
              <label class="block text-sm font-medium text-surface-700 dark:text-surface-200 mb-1.5">{{ $t('coupons.code') }} *</label>
              <div class="relative">
                <input v-model="form.code" maxlength="20" :placeholder="autoGeneratedCode"
                  class="w-full px-3.5 py-2.5 border border-surface-200 dark:border-surface-600 bg-white dark:bg-surface-700 text-surface-800 dark:text-white rounded-lg text-sm focus:ring-2 focus:ring-purple-500/50 transition-all uppercase" />
                <button type="button" @click="generateCode" class="absolute right-2 top-1/2 -translate-y-1/2 p-1.5 text-surface-400 hover:text-purple-500 transition-colors" title="Generate code">
                  <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/></svg>
                </button>
              </div>
            </div>
          </div>

          <!-- Description -->
          <div>
            <label class="block text-sm font-medium text-surface-700 dark:text-surface-200 mb-1.5">{{ $t('coupons.description') }}</label>
            <textarea v-model="form.description" rows="2" maxlength="500"
              class="w-full px-3.5 py-2.5 border border-surface-200 dark:border-surface-600 bg-white dark:bg-surface-700 text-surface-800 dark:text-white rounded-lg text-sm focus:ring-2 focus:ring-purple-500/50 resize-none transition-all"></textarea>
          </div>

          <!-- Discount Type & Value -->
          <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div>
              <label class="block text-sm font-medium text-surface-700 dark:text-surface-200 mb-1.5">{{ $t('coupons.discountType') }} *</label>
              <select v-model="form.discountType"
                class="w-full px-3.5 py-2.5 border border-surface-200 dark:border-surface-600 bg-white dark:bg-surface-700 text-surface-800 dark:text-white rounded-lg text-sm focus:ring-2 focus:ring-purple-500/50">
                <option value="percentage">{{ $t('coupons.percentage') }}</option>
                <option value="fixed">{{ $t('coupons.fixed') }}</option>
                <option value="free_shipping">{{ $t('coupons.freeShipping') }}</option>
              </select>
            </div>
            <div>
              <label class="block text-sm font-medium text-surface-700 dark:text-surface-200 mb-1.5">{{ $t('coupons.discountValue') }} *</label>
              <div class="relative">
                <input v-model.number="form.discountValue" type="number" min="0" :max="form.discountType === 'percentage' ? 100 : undefined" required
                  class="w-full px-3.5 py-2.5 pr-8 border border-surface-200 dark:border-surface-600 bg-white dark:bg-surface-700 text-surface-800 dark:text-white rounded-lg text-sm focus:ring-2 focus:ring-purple-500/50 transition-all" />
                <span class="absolute right-3 top-1/2 -translate-y-1/2 text-surface-400 text-sm">{{ form.discountType === 'percentage' ? '%' : '$' }}</span>
              </div>
            </div>
            <div v-if="form.discountType === 'percentage'">
              <label class="block text-sm font-medium text-surface-700 dark:text-surface-200 mb-1.5">{{ $t('coupons.maxDiscount') }}</label>
              <div class="relative">
                <input v-model.number="form.maximumDiscount" type="number" min="0"
                  class="w-full px-3.5 py-2.5 pr-8 border border-surface-200 dark:border-surface-600 bg-white dark:bg-surface-700 text-surface-800 dark:text-white rounded-lg text-sm focus:ring-2 focus:ring-purple-500/50 transition-all" />
                <span class="absolute right-3 top-1/2 -translate-y-1/2 text-surface-400 text-sm">$</span>
              </div>
            </div>
          </div>

          <!-- Min Purchase & Limits -->
          <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div>
              <label class="block text-sm font-medium text-surface-700 dark:text-surface-200 mb-1.5">{{ $t('coupons.minPurchase') }}</label>
              <div class="relative">
                <input v-model.number="form.minimumPurchase" type="number" min="0" step="0.01"
                  class="w-full px-3.5 py-2.5 pr-8 border border-surface-200 dark:border-surface-600 bg-white dark:bg-surface-700 text-surface-800 dark:text-white rounded-lg text-sm focus:ring-2 focus:ring-purple-500/50 transition-all" />
                <span class="absolute right-3 top-1/2 -translate-y-1/2 text-surface-400 text-sm">$</span>
              </div>
            </div>
            <div>
              <label class="block text-sm font-medium text-surface-700 dark:text-surface-200 mb-1.5">{{ $t('coupons.usageLimit') }}</label>
              <input v-model.number="form.usageLimit" type="number" min="0"
                class="w-full px-3.5 py-2.5 border border-surface-200 dark:border-surface-600 bg-white dark:bg-surface-700 text-surface-800 dark:text-white rounded-lg text-sm focus:ring-2 focus:ring-purple-500/50 transition-all" />
            </div>
            <div>
              <label class="block text-sm font-medium text-surface-700 dark:text-surface-200 mb-1.5">{{ $t('coupons.limitPerUser') }}</label>
              <input v-model.number="form.limitPerUser" type="number" min="1"
                class="w-full px-3.5 py-2.5 border border-surface-200 dark:border-surface-600 bg-white dark:bg-surface-700 text-surface-800 dark:text-white rounded-lg text-sm focus:ring-2 focus:ring-purple-500/50 transition-all" />
            </div>
          </div>

          <!-- Date Range -->
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-surface-700 dark:text-surface-200 mb-1.5">{{ $t('coupons.startDate') }} *</label>
              <input v-model="form.startDate" type="datetime-local" required
                class="w-full px-3.5 py-2.5 border border-surface-200 dark:border-surface-600 bg-white dark:bg-surface-700 text-surface-800 dark:text-white rounded-lg text-sm focus:ring-2 focus:ring-purple-500/50 transition-all" />
            </div>
            <div>
              <label class="block text-sm font-medium text-surface-700 dark:text-surface-200 mb-1.5">{{ $t('coupons.endDate') }} *</label>
              <input v-model="form.endDate" type="datetime-local" required
                class="w-full px-3.5 py-2.5 border border-surface-200 dark:border-surface-600 bg-white dark:bg-surface-700 text-surface-800 dark:text-white rounded-lg text-sm focus:ring-2 focus:ring-purple-500/50 transition-all" />
            </div>
          </div>

          <!-- Banner Image & Theme Color -->
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-surface-700 dark:text-surface-200 mb-1.5">{{ $t('coupons.bannerImage') }}</label>
              <input ref="fileInput" type="file" accept="image/*" @change="handleFile"
                class="w-full text-sm text-surface-500 file:mr-4 file:py-2.5 file:px-4 file:rounded-lg file:border-0 file:text-sm file:font-medium file:bg-purple-50 dark:file:bg-purple-900/30 file:text-purple-600 dark:file:text-purple-400 hover:file:bg-purple-100 transition-all" />
              <div v-if="imagePreview || (coupon && coupon.bannerImage)" class="mt-2 relative w-full aspect-video rounded-xl overflow-hidden border-2 border-surface-200 dark:border-surface-600">
                <img :src="imagePreview || coupon?.bannerImage?.secure_url" class="w-full h-full object-cover" />
                <button v-if="imagePreview" type="button" @click="removeImage" class="absolute top-2 right-2 w-6 h-6 bg-red-500 text-white rounded-full flex items-center justify-center text-xs hover:bg-red-600 shadow-sm">×</button>
              </div>
            </div>
            <div>
              <label class="block text-sm font-medium text-surface-700 dark:text-surface-200 mb-1.5">{{ $t('coupons.themeColor') }}</label>
              <div class="flex items-center gap-3">
                <input v-model="form.themeColor" type="color"
                  class="w-12 h-12 rounded-xl border border-surface-200 dark:border-surface-600 cursor-pointer" />
                <span class="text-sm text-surface-400">{{ form.themeColor }}</span>
              </div>
            </div>
          </div>

          <!-- Toggles Section -->
          <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-3">
            <label class="flex items-center gap-2.5 p-3 bg-surface-50 dark:bg-surface-700/30 rounded-lg cursor-pointer hover:bg-surface-100 dark:hover:bg-surface-700/50 transition-colors">
              <input type="checkbox" v-model="form.autoApply" class="w-4 h-4 text-purple-500 rounded focus:ring-purple-500" />
              <span class="text-sm text-surface-700 dark:text-surface-200">{{ $t('coupons.autoApply') }}</span>
            </label>
            <label class="flex items-center gap-2.5 p-3 bg-surface-50 dark:bg-surface-700/30 rounded-lg cursor-pointer hover:bg-surface-100 dark:hover:bg-surface-700/50 transition-colors">
              <input type="checkbox" v-model="form.isHighlighted" class="w-4 h-4 text-purple-500 rounded focus:ring-purple-500" />
              <span class="text-sm text-surface-700 dark:text-surface-200">{{ $t('coupons.featured') }}</span>
            </label>
            <label class="flex items-center gap-2.5 p-3 bg-surface-50 dark:bg-surface-700/30 rounded-lg cursor-pointer hover:bg-surface-100 dark:hover:bg-surface-700/50 transition-colors">
              <input type="checkbox" v-model="form.stackable" class="w-4 h-4 text-purple-500 rounded focus:ring-purple-500" />
              <span class="text-sm text-surface-700 dark:text-surface-200">{{ $t('coupons.stackable') }}</span>
            </label>
            <label class="flex items-center gap-2.5 p-3 bg-surface-50 dark:bg-surface-700/30 rounded-lg cursor-pointer hover:bg-surface-100 dark:hover:bg-surface-700/50 transition-colors">
              <input type="checkbox" v-model="form.allowGuest" class="w-4 h-4 text-purple-500 rounded focus:ring-purple-500" />
              <span class="text-sm text-surface-700 dark:text-surface-200">{{ $t('coupons.allowGuest') }}</span>
            </label>
            <label class="flex items-center gap-2.5 p-3 bg-surface-50 dark:bg-surface-700/30 rounded-lg cursor-pointer hover:bg-surface-100 dark:hover:bg-surface-700/50 transition-colors">
              <input type="checkbox" v-model="form.newCustomerOnly" class="w-4 h-4 text-purple-500 rounded focus:ring-purple-500" />
              <span class="text-sm text-surface-700 dark:text-surface-200">{{ $t('coupons.newCustomer') }}</span>
            </label>
            <label class="flex items-center gap-2.5 p-3 bg-surface-50 dark:bg-surface-700/30 rounded-lg cursor-pointer hover:bg-surface-100 dark:hover:bg-surface-700/50 transition-colors">
              <input type="checkbox" v-model="form.firstOrderOnly" class="w-4 h-4 text-purple-500 rounded focus:ring-purple-500" />
              <span class="text-sm text-surface-700 dark:text-surface-200">{{ $t('coupons.firstOrder') }}</span>
            </label>
          </div>

          <!-- Priority -->
          <div>
            <label class="block text-sm font-medium text-surface-700 dark:text-surface-200 mb-1.5">{{ $t('coupons.priority') }} ({{ form.priority }})</label>
            <input v-model.number="form.priority" type="range" min="0" max="100"
              class="w-full h-2 bg-surface-200 dark:bg-surface-600 rounded-lg appearance-none cursor-pointer accent-purple-500" />
          </div>

          <!-- Notification Section -->
          <div v-if="!isEditing" class="border-t border-surface-200 dark:border-surface-700 pt-5">
            <h4 class="text-sm font-bold text-surface-800 dark:text-white mb-3">{{ $t('coupons.notificationSettings') }}</h4>
            <label class="flex items-center gap-2.5 p-3 bg-surface-50 dark:bg-surface-700/30 rounded-lg cursor-pointer mb-3">
              <input type="checkbox" v-model="sendNotification" class="w-4 h-4 text-purple-500 rounded focus:ring-purple-500" />
              <span class="text-sm text-surface-700 dark:text-surface-200">{{ $t('coupons.sendNotification') }}</span>
            </label>
            <div v-if="sendNotification" class="space-y-4 pl-3 border-l-2 border-purple-300 dark:border-purple-700">
              <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label class="block text-sm font-medium text-surface-700 dark:text-surface-200 mb-1.5">{{ $t('coupons.notifTitle') }}</label>
                  <input v-model="notifTitle" maxlength="200"
                    class="w-full px-3.5 py-2.5 border border-surface-200 dark:border-surface-600 bg-white dark:bg-surface-700 text-surface-800 dark:text-white rounded-lg text-sm focus:ring-2 focus:ring-purple-500/50 transition-all" />
                </div>
                <div>
                  <label class="block text-sm font-medium text-surface-700 dark:text-surface-200 mb-1.5">{{ $t('coupons.notifMessage') }}</label>
                  <input v-model="notifMessage" maxlength="500"
                    class="w-full px-3.5 py-2.5 border border-surface-200 dark:border-surface-600 bg-white dark:bg-surface-700 text-surface-800 dark:text-white rounded-lg text-sm focus:ring-2 focus:ring-purple-500/50 transition-all" />
                </div>
              </div>
              <div>
                <label class="block text-sm font-medium text-surface-700 dark:text-surface-200 mb-1.5">{{ $t('coupons.notifButtonText') }}</label>
                <input v-model="notifButtonText" maxlength="30"
                  class="w-full px-3.5 py-2.5 border border-surface-200 dark:border-surface-600 bg-white dark:bg-surface-700 text-surface-800 dark:text-white rounded-lg text-sm focus:ring-2 focus:ring-purple-500/50 transition-all" />
              </div>
            </div>
          </div>

          <!-- Preview Card -->
          <div class="border-t border-surface-200 dark:border-surface-700 pt-5">
            <h4 class="text-sm font-bold text-surface-800 dark:text-white mb-3">{{ $t('coupons.preview') }}</h4>
            <div class="relative rounded-2xl overflow-hidden border border-surface-200 dark:border-surface-600 max-w-sm mx-auto">
              <div class="p-5 text-white" :style="{ background: form.themeColor }">
                <div class="text-center space-y-2">
                  <p class="text-3xl font-black">
                    {{ form.discountType === 'percentage' ? `${form.discountValue}%` : form.discountType === 'fixed' ? `$${form.discountValue}` : '🚚' }}
                  </p>
                  <p class="text-lg font-bold">{{ form.discountType === 'free_shipping' ? 'FREE SHIPPING' : 'OFF' }}</p>
                  <p v-if="form.name" class="text-sm opacity-90">{{ form.name }}</p>
                  <div v-if="form.code" class="inline-block px-4 py-1.5 bg-white/20 backdrop-blur-sm rounded-lg text-sm font-mono font-bold tracking-wider">
                    {{ form.code }}
                  </div>
                  <p v-if="form.minimumPurchase > 0" class="text-xs opacity-75">Min. purchase: ${{ form.minimumPurchase }}</p>
                </div>
              </div>
            </div>
          </div>

          <!-- Submit Error -->
          <div v-if="submitError" class="bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 text-sm p-3.5 rounded-xl">{{ submitError }}</div>
        </form>
      </div>

      <!-- Footer -->
      <div class="flex items-center gap-3 px-6 py-4 border-t border-surface-200 dark:border-surface-700 bg-surface-50 dark:bg-surface-800/50 flex-shrink-0">
        <button type="button" @click="$emit('close')" class="flex-1 py-2.5 border border-surface-200 dark:border-surface-600 text-surface-700 dark:text-surface-200 rounded-lg text-sm font-medium hover:bg-white dark:hover:bg-surface-700 transition-all">{{ $t('common.cancel') }}</button>
        <button type="submit" @click="save" :disabled="saving" class="flex-1 py-2.5 bg-purple-500 text-white rounded-lg text-sm font-medium hover:bg-purple-600 disabled:opacity-50 transition-all shadow-sm">
          <span v-if="saving" class="flex items-center justify-center gap-2">
            <svg class="w-4 h-4 animate-spin" viewBox="0 0 24 24" fill="none"><circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"/><path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/></svg>
            {{ $t('common.saving') }}
          </span>
          <span v-else>{{ isEditing ? $t('coupons.updateCoupon') : $t('coupons.createCoupon') }}</span>
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useCouponStore, type Coupon } from '@/stores/coupon'

const props = defineProps<{
  visible: boolean
  coupon: Coupon | null
}>()

const emit = defineEmits<{
  close: []
  saved: []
}>()

const store = useCouponStore()

const isEditing = computed(() => !!props.coupon)

const autoGeneratedCode = ref('')

function generateCode() {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
  let code = ''
  for (let i = 0; i < 8; i++) {
    code += chars.charAt(Math.floor(Math.random() * chars.length))
  }
  form.value.code = code
}

const form = ref({
  name: '',
  code: '',
  description: '',
  discountType: 'percentage' as 'percentage' | 'fixed' | 'free_shipping',
  discountValue: 10,
  minimumPurchase: 0,
  maximumDiscount: 0,
  startDate: '',
  endDate: '',
  usageLimit: 0,
  limitPerUser: 1,
  applicableProducts: [] as string[],
  applicableCategories: [] as string[],
  excludedProducts: [] as string[],
  excludedCategories: [] as string[],
  applicableUsers: [] as string[],
  newCustomerOnly: false,
  firstOrderOnly: false,
  allowGuest: false,
  stackable: false,
  priority: 0,
  autoApply: false,
  isHighlighted: false,
  themeColor: '#6366F1',
})

const sendNotification = ref(false)
const notifTitle = ref('')
const notifMessage = ref('')
const notifButtonText = ref('')

const saving = ref(false)
const submitError = ref<string | null>(null)
const fileInput = ref<HTMLInputElement | null>(null)
const selectedFile = ref<File | null>(null)
const imagePreview = ref<string | null>(null)

watch(() => props.visible, (val) => {
  if (val) {
    if (props.coupon) {
      // Editing mode
      const c = props.coupon
      form.value = {
        name: c.name,
        code: c.code,
        description: c.description || '',
        discountType: c.discountType,
        discountValue: c.discountValue,
        minimumPurchase: c.minimumPurchase,
        maximumDiscount: c.maximumDiscount,
        startDate: toDatetimeLocal(c.startDate),
        endDate: toDatetimeLocal(c.endDate),
        usageLimit: c.usageLimit || 0,
        limitPerUser: c.limitPerUser || 1,
        applicableProducts: c.applicableProducts?.map((p: any) => p._id || p) || [],
        applicableCategories: c.applicableCategories?.map((cat: any) => cat._id || cat) || [],
        excludedProducts: c.excludedProducts?.map((p: any) => p._id || p) || [],
        excludedCategories: c.excludedCategories?.map((cat: any) => cat._id || cat) || [],
        applicableUsers: c.applicableUsers?.map((u: any) => u._id || u) || [],
        newCustomerOnly: c.newCustomerOnly,
        firstOrderOnly: c.firstOrderOnly,
        allowGuest: c.allowGuest,
        stackable: c.stackable,
        priority: c.priority || 0,
        autoApply: c.autoApply,
        isHighlighted: c.isHighlighted,
        themeColor: c.themeColor || '#6366F1',
      }
      // Set a default endDate for convenience
    } else {
      const now = new Date()
      const start = new Date(now.getTime() - now.getTimezoneOffset() * 60000)
      const end = new Date(start.getTime() + 7 * 24 * 60 * 60 * 1000)
      form.value = {
        name: '',
        code: '',
        description: '',
        discountType: 'percentage',
        discountValue: 10,
        minimumPurchase: 0,
        maximumDiscount: 0,
        startDate: start.toISOString().slice(0, 16),
        endDate: end.toISOString().slice(0, 16),
        usageLimit: 0,
        limitPerUser: 1,
        applicableProducts: [],
        applicableCategories: [],
        excludedProducts: [],
        excludedCategories: [],
        applicableUsers: [],
        newCustomerOnly: false,
        firstOrderOnly: false,
        allowGuest: false,
        stackable: false,
        priority: 0,
        autoApply: false,
        isHighlighted: false,
        themeColor: '#6366F1',
      }
      generateCode()
    }
    selectedFile.value = null
    imagePreview.value = null
    submitError.value = null
    sendNotification.value = false
    notifTitle.value = ''
    notifMessage.value = ''
    notifButtonText.value = ''
  }
})

function toDatetimeLocal(dateStr: string): string {
  const d = new Date(dateStr)
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`
}

function handleFile(e: Event) {
  const target = e.target as HTMLInputElement
  if (target.files?.[0]) {
    selectedFile.value = target.files[0]
    const reader = new FileReader()
    reader.onload = (ev) => { imagePreview.value = ev.target?.result as string }
    reader.readAsDataURL(target.files[0])
  }
}

function removeImage() {
  selectedFile.value = null
  imagePreview.value = null
  if (fileInput.value) fileInput.value.value = ''
}

async function save() {
  if (form.value.startDate >= form.value.endDate) {
    submitError.value = 'End date must be after start date'
    return
  }

  saving.value = true
  submitError.value = null

  try {
    const fd = new FormData()
    fd.append('name', form.value.name)
    fd.append('code', form.value.code)
    fd.append('description', form.value.description)
    fd.append('discountType', form.value.discountType)
    fd.append('discountValue', String(form.value.discountValue))
    fd.append('minimumPurchase', String(form.value.minimumPurchase))
    fd.append('maximumDiscount', String(form.value.maximumDiscount))
    fd.append('startDate', form.value.startDate)
    fd.append('endDate', form.value.endDate)
    fd.append('usageLimit', String(form.value.usageLimit))
    fd.append('limitPerUser', String(form.value.limitPerUser))
    fd.append('applicableProducts', JSON.stringify(form.value.applicableProducts))
    fd.append('applicableCategories', JSON.stringify(form.value.applicableCategories))
    fd.append('excludedProducts', JSON.stringify(form.value.excludedProducts))
    fd.append('excludedCategories', JSON.stringify(form.value.excludedCategories))
    fd.append('applicableUsers', JSON.stringify(form.value.applicableUsers))
    fd.append('newCustomerOnly', String(form.value.newCustomerOnly))
    fd.append('firstOrderOnly', String(form.value.firstOrderOnly))
    fd.append('allowGuest', String(form.value.allowGuest))
    fd.append('stackable', String(form.value.stackable))
    fd.append('priority', String(form.value.priority))
    fd.append('autoApply', String(form.value.autoApply))
    fd.append('isHighlighted', String(form.value.isHighlighted))
    fd.append('themeColor', form.value.themeColor)
    fd.append('status', 'active')

    if (selectedFile.value) {
      fd.append('bannerImage', selectedFile.value)
    }

    // Notification fields (create only)
    if (!isEditing.value) {
      fd.append('sendNotification', String(sendNotification.value))
      fd.append('notificationTitle', notifTitle.value)
      fd.append('notificationMessage', notifMessage.value)
      fd.append('notificationButtonText', notifButtonText.value)
      fd.append('sendTo', 'all')
    }

    let result: { success: boolean; message: string }
    if (isEditing.value) {
      result = await store.updateCoupon(props.coupon!._id, fd)
    } else {
      result = await store.createCoupon(fd)
    }

    if (result.success) {
      emit('saved')
    } else {
      submitError.value = result.message
    }
  } catch (err: any) {
    submitError.value = err.message || 'Failed to save coupon'
  } finally {
    saving.value = false
  }
}
</script>

<style scoped>
.animate-slide-in-right {
  animation: slideInRight 0.3s cubic-bezier(0.16, 1, 0.3, 1);
}
@keyframes slideInRight {
  from { transform: translateX(100%); opacity: 0; }
  to { transform: translateX(0); opacity: 1; }
}
</style>
